name: Build the Juju Doctor binary

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/canonical/*
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64
  build-app:
    name: Build the juju-doctor binary
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/canonical/*
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Build binary
        run: |
          make build
      - name: Test binary
        run: |
          ./bin/juju-doctor --help